CREATE TABLE IF NOT EXISTS `resonance_zone_entries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `is_enabled` tinyint(4) NOT NULL DEFAULT 1,
  `cell_id` int(10) unsigned NOT NULL,
  `x` float NOT NULL,
  `y` float NOT NULL,
  `z` float NOT NULL,
  `qx` float NOT NULL,
  `qy` float NOT NULL,
  `qz` float NOT NULL,
  `qw` float NOT NULL,
  `radius` float NOT NULL,
  `max_distance` float NOT NULL,
  `name` varchar(64) NOT NULL DEFAULT '',
  `shroud_event_key` varchar(64) NOT NULL DEFAULT '',
  `storm_event_key` varchar(64) NOT NULL DEFAULT '',
  `modified_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `zone_type` smallint(6) NOT NULL DEFAULT 0,
  `event_key` varchar(64) DEFAULT NULL,
  `zone_key` varchar(64) NOT NULL,
  `param_a` float DEFAULT NULL,
  `param_b` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_rz_zone_key` (`zone_key`),
  KEY `idx_sz_enabled` (`is_enabled`),
  KEY `idx_sz_cell` (`cell_id`),
  KEY `idx_sz_modified` (`modified_at`),
  KEY `idx_rz_event_key` (`event_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
