namespace ACE.Entity.Enum;

public enum CombatAbility
{
    None,
    PerceiveThreats,
    Stealth,
    Phalanx,
    Provoke,
    Riposte,
    Fury,
    Backstab,
    SteadyShot,
    Smokescreen,
    Relentless,
    Overload,
    Battery,
    Reflect,
    EnchantedWeapon,
    WeaponMaster,
    SlashThrustToggle,
    FocusedTaunt,
    AreaTaunt,
    FeignInjury,
    Vanish,
    ExposePhysicalWeakness,
    ExposeMagicalWeakness,
    Multishot,
    ActivatedCombatAbilities,
    ManaBarrier,
    Shroud,
    EvasiveStance,
    EnchantedBlade,
    Aegis,
}
