namespace ACE.Entity.Enum
{
    public enum CombatAbility
    {
        None,
        PerceiveThreats,
        Stealth,
        Phalanx,
        Provoke,
        Parry,
        Reckless,
        Backstab,
        Powershot,
        Smokescreen,
        IronFist,
        Overload,
        Battery,
        Reflect,
        EnchantedWeapon,
        Deceive,
        SlashThrustToggle,
        FocusedTaunt,
        AreaTaunt,
        FeignInjury,
        Vanish,
        ExposePhysicalWeakness,
        ExposeMagicalWeakness,
    }
}
