using System.Collections.Generic;
using ACE.Entity.Enum;

namespace ACE.Server.Entity;

/// <summary>
/// SPEC BONUS - War/Life Magic: the advanced spells, which need their school specialized to learn and cast
/// </summary>
internal static class AdvancedSpells
{
    private static readonly HashSet<SpellCategory> Categories =
    [
        // War
        SpellCategory.AcidBurst,
        SpellCategory.BludgeoningBurst,
        SpellCategory.ColdBurst,
        SpellCategory.ElectricBurst,
        SpellCategory.FireBurst,
        SpellCategory.PiercingBurst,
        SpellCategory.SlashingBurst,
        SpellCategory.AcidBlast,
        SpellCategory.BludgeoningBlast,
        SpellCategory.ColdBlast,
        SpellCategory.ElectricBlast,
        SpellCategory.FireBlast,
        SpellCategory.PiercingBlast,
        SpellCategory.SlashingBlast,
        SpellCategory.AcidVolley,
        SpellCategory.BladeVolley,
        SpellCategory.BludgeoningVolley,
        SpellCategory.FlameVolley,
        SpellCategory.ForceVolley,
        SpellCategory.FrostVolley,
        SpellCategory.LightningVolley,
        SpellCategory.AcidStreak,
        SpellCategory.BludgeoningStreak,
        SpellCategory.ColdStreak,
        SpellCategory.ElectricStreak,
        SpellCategory.FireStreak,
        SpellCategory.PiercingStreak,
        SpellCategory.SlashingStreak,
        SpellCategory.AcidWall,
        SpellCategory.BludgeoningWall,
        SpellCategory.ColdWall,
        SpellCategory.ElectricWall,
        SpellCategory.FireWall,
        SpellCategory.PiercingWall,
        SpellCategory.SlashingWall,
        SpellCategory.AcidRing,
        SpellCategory.BludgeoningRing,
        SpellCategory.ColdRing,
        SpellCategory.ElectricRing,
        SpellCategory.FireRing,
        SpellCategory.PiercingRing,
        SpellCategory.SlashingRing,
        // Life
        SpellCategory.NetherDamageRatingLowering,
        SpellCategory.NetherDamageHealingReductionRaising,
        SpellCategory.NetherDamageOverTimeRaising,
        SpellCategory.NetherDamageOverTimeRaising2,
        SpellCategory.NetherDamageOverTimeRaising3,
    ];

    private static readonly HashSet<SpellId> SpellIds =
    [
        // War

        // Life
        SpellId.HealFellow1,
        SpellId.DispelLifeBadFellow1,
        SpellId.FellowshipHeal1,
        SpellId.FellowshipHeal2,
        SpellId.FellowshipHeal3,
        SpellId.FellowshipHeal4,
        SpellId.FellowshipHeal5,
        SpellId.FellowshipHeal6,
        SpellId.FellowshipHeal7,
        SpellId.FellowshipRevitalize1,
        SpellId.FellowshipRevitalize2,
        SpellId.FellowshipRevitalize3,
        SpellId.FellowshipRevitalize4,
        SpellId.FellowshipRevitalize5,
        SpellId.FellowshipRevitalize6,
        SpellId.FellowshipRevitalize7,
        SpellId.FellowshipManaBoost1,
        SpellId.FellowshipManaBoost2,
        SpellId.FellowshipManaBoost3,
        SpellId.FellowshipManaBoost4,
        SpellId.FellowshipManaBoost5,
        SpellId.FellowshipManaBoost6,
        SpellId.FellowshipManaBoost7,
        SpellId.HealthBolt1,
        SpellId.HealthBolt2,
        SpellId.HealthBolt3,
        SpellId.HealthBolt4,
        SpellId.HealthBolt5,
        SpellId.HealthBolt6,
        SpellId.HealthBolt7,
        SpellId.StaminaBolt1,
        SpellId.StaminaBolt2,
        SpellId.StaminaBolt3,
        SpellId.StaminaBolt4,
        SpellId.StaminaBolt5,
        SpellId.StaminaBolt6,
        SpellId.StaminaBolt7,
        SpellId.ManaBolt1,
        SpellId.ManaBolt2,
        SpellId.ManaBolt3,
        SpellId.ManaBolt4,
        SpellId.ManaBolt5,
        SpellId.ManaBolt6,
        SpellId.ManaBolt7,
        SpellId.VitalityMend1,
        SpellId.VitalityMend2,
        SpellId.VitalityMend3,
        SpellId.VitalityMend4,
        SpellId.VitalityMend5,
        SpellId.VitalityMend6,
        SpellId.VitalityMend7,
        SpellId.VigorMend1,
        SpellId.VigorMend2,
        SpellId.VigorMend3,
        SpellId.VigorMend4,
        SpellId.VigorMend5,
        SpellId.VigorMend6,
        SpellId.VigorMend7,
        SpellId.ClarityMend1,
        SpellId.ClarityMend2,
        SpellId.ClarityMend3,
        SpellId.ClarityMend4,
        SpellId.ClarityMend5,
        SpellId.ClarityMend6,
        SpellId.ClarityMend7,
        SpellId.VitalityMendOther1,
        SpellId.VitalityMendOther2,
        SpellId.VitalityMendOther3,
        SpellId.VitalityMendOther4,
        SpellId.VitalityMendOther5,
        SpellId.VitalityMendOther6,
        SpellId.VitalityMendOther7,
        SpellId.VigorMendOther1,
        SpellId.VigorMendOther2,
        SpellId.VigorMendOther3,
        SpellId.VigorMendOther4,
        SpellId.VigorMendOther5,
        SpellId.VigorMendOther6,
        SpellId.VigorMendOther7,
        SpellId.ClarityMendOther1,
        SpellId.ClarityMendOther2,
        SpellId.ClarityMendOther3,
        SpellId.ClarityMendOther4,
        SpellId.ClarityMendOther5,
        SpellId.ClarityMendOther6,
        SpellId.ClarityMendOther7,
    ];

    public static bool IsAdvanced(SpellCategory category, uint spellId)
    {
        return Categories.Contains(category) || SpellIds.Contains((SpellId)spellId);
    }
}
